version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll
    container_name: jekyll_site_1
    volumes:
      - .:/srv/jekyll:Z
    ports:
      - "4000:4000"
    command: jekyll serve
    restart: unless-stopped
