services:
  jekyll:
    build: .
    container_name: jekyll_site_2
    ports:
      - "4000:4000"
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /srv/jekyll
